### ISSUE TITLE
Check for AVX2?

### ISSUE THREAD

**Issue by jparismorgan** [Mysticial/FeatureDetector#16]
Hi there, it would be nice if we could add support for AVX2 as well, unless it's there and I missed it? Thanks!

**Comment by Mysticial** [comment]
It's there, under the "SIMD: 256-bit" section.

**Comment by jparismorgan** [comment]
Oh, I see, thank you! So I am trying to use this at runtime to determine which version of [llama.cpp](https://github.com/ggerganov/llama.cpp) to use (i.e. I will have prebuilt 4 different executables). It compiles for no AVX, AVX, AVX2, and AVX512 (you can see that in [this release](https://github.com/ggerganov/llama.cpp/releases/tag/b1620)). For an example output below:
```
CPU Vendor String: GenuineIntel

CPU Vendor:
    AMD         = No
    Intel       = Yes

OS Features:
    64-bit      = Yes
    OS AVX      = Yes
    OS AVX512   = No

Hardware Features:
    MMX         = Yes
    x64         = Yes
    ABM         = Yes
    RDRAND      = Yes
    BMI1        = Yes
    BMI2        = Yes
    ADX         = No
    MPX         = No
    PREFETCHWT1 = No

SIMD: 128-bit
    SSE         = Yes
    SSE2        = Yes
    SSE3        = Yes
    SSSE3       = Yes
    SSE4a       = No
    SSE4.1      = Yes
    SSE4.2      = Yes
    AES-NI      = Yes
    SHA         = No

SIMD: 256-bit
    AVX         = Yes
    XOP         = No
    FMA3        = Yes
    FMA4        = No
    AVX2        = Yes

SIMD: 512-bit
    AVX512-F    = No
    AVX512-CD   = No
    AVX512-PF   = No
    AVX512-ER   = No
    AVX512-VL   = No
    AVX512-BW   = No
    AVX512-DQ   = No
    AVX512-IFMA = No
    AVX512-VBMI = No

Summary:
    Safe to use AVX:     Yes
    Safe to use AVX512:  No
```
Would it be safe to say:
* Use AVX512 if `Safe to use AVX512:  Yes`
* Else use AVX2 if `AVX2        = Yes`
* Else use AVX if `Safe to use AVX:     Yes`

Thank you!

**Comment by Mysticial** [comment]
To run AVX2, you need all of these:

- Safe to use AVX. (which checks for "AVX" and "OS AVX")
- "AVX2"

So 3 flags total.

Same applies to AVX512. The "safe to use AVX512" only means AVX512-F. You also need to check the variants that you intend to use.

**Comment by jparismorgan** [comment]
Thank you! I don't see which variant of AVX512 mentioned, I can ask in llama.cpp, but curious if there is a "standard" one referred to when someone says AVX512? 

I do see `__AVX512F__` in the code, so perhaps it is `AVX512-F`?  Though I also do see `ggml_cpu_has_avx512_vbmi` and `ggml_cpu_has_avx512_vnni` which are not mentioned here.
* https://github.com/search?q=repo%3Aggerganov%2Fllama.cpp%20AVX512&type=code
* https://github.com/search?q=repo%3Aggerganov%2Fggml+AVX512&type=code

Either way, thank you for the help.
