### ISSUE TITLE
New feature: TensorFlow style feature warning

### ISSUE THREAD

**Issue by henryiii** [Mysticial/FeatureDetector#4]
TensorFlow has a nice feature where it warns you if a feature set is available but not compiled for. It would be relatively trivial, I believe, to add a method that checks the defines ([For example](http://stackoverflow.com/questions/28939652/how-to-detect-sse-avx-avx2-availability-at-compile-time)), and then gives a list of warnings for un-optimized code.

Something like:
```
Warning: hardware supports AVX512 but not enabled in compilation
```

**Comment by Mysticial** [comment]
I feel this is beyond the scope of the project. Lemme thing about this later.

**Comment by henryiii** [comment]
Feel free to check out the PRs for this and CMake. I'm using them successfully at the moment in a branch of [GooFit](https://github.com/GooFit/GooFit/tree/cleanup).
