### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by henryiii** [Mysticial/FeatureDetector#5]
Please include a CMakeLists.txt file, preferably for a version of CMake > 3.4. Then it would be easy to include this project in another project. See https://github.com/GooFit/Minuit2/blob/master/CMakeLists.txt for an example of a simple CMakeLists. It could live besides SCONS.

**Comment by henryiii** [comment]
PS: I could probably put together a PR if you are interested.

**Comment by Mysticial** [comment]
I'll take a look at this when I get the time. But be aware that I cannot maintain support for toolsets that I don't use. So they will probably break in the future and I won't know.
