### ISSUE TITLE
Instruction for compilation

### ISSUE THREAD

**Issue by Magalame** [Mysticial/FeatureDetector#9]
HI!
I was wondering how does one compile/run the feature detector?

**Comment by IvanBoyko** [comment]
Last time I used it, this was working:
```
cmake .
cmake --build .
```

**Comment by IvanBoyko** [comment]
I've also automated it in the CI/CD pipeline.
Can share if needed.

**Comment by Magalame** [comment]
It's alright thanks, it worked out perfectly :)

**Comment by ThrashAbaddon** [comment]
@Magalame Please close the issue as it seems to be solved.
